### ISSUE TITLE
Support line items with a product discount

### ISSUE THREAD

**Issue by DownChapel** [dove-technology/commercetools-discounts-extension#5]
- [x] Are commercetools product discounts supported alongside Direct Discounts in the same cart?
- [x] If yes - Review if product discounts cause `discountedPricePerQuantity` to be used? If not, should be fine, just review mapping of prices
- [x] If no - review mapping of line item prices to Dovetech.

**Comment by stevenhayes** [comment]
See screenshot - so anwsers are basically yes and yes to above points 👍🏼 

![Image](https://github.com/user-attachments/assets/aef937b8-ab55-48c6-852b-2e2f35ac0514)
